# Generated by Django 4.2.13 on 2024-07-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Utilizator", "verbose_name_plural": "Utilizatori"},
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                editable=False,
                help_text="Nu utilizăm acest câmp",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="nume utilizator",
            ),
        ),
    ]
