# Generated by Django 4.2.13 on 2024-07-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_is_ngohub_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Nu utilizăm acest câmp",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="nume utilizator",
            ),
        ),
    ]
