# Generated by Django 4.2.16 on 2024-10-21 12:48

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0010_user_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProxy",
            fields=[],
            options={
                "verbose_name": "Grup",
                "verbose_name_plural": "Grupuri",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_ngohub_user",
            field=models.BooleanField(default=False, verbose_name="este utilizator NGO Hub"),
        ),
    ]
