name: votong_dev

services:

  db:
    extends:
      file: docker-compose.base.yml
      service: db_base_psql

  backend:
    extends:
      file: docker-compose.base.yml
      service: backend_base
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.backend.dev
    volumes:
      - ./backend:/var/www/votong/backend
    depends_on:
      - db
    ports:
      - "5678:5678"

volumes:
  votong_psql:
