name: votong_prod

services:

  db:
    extends:
      file: docker-compose.base.yml
      service: db_base_psql
    container_name: votong_db

  backend:
    extends:
      file: docker-compose.base.yml
      service: backend_base
    container_name: votong_backend
    build:
      context: .
      dockerfile: ./docker/dockerfiles/Dockerfile.backend
    volumes:
      - ./backend/media:/var/www/votong/backend/media
    depends_on:
      - db

volumes:
  votong_psql:
