version: '3.7'

services:
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: dockerize -wait tcp://db:5432 -timeout 90s
    env_file:
      - .env
    ports:
      - "8010:8010"
    volumes:
      - ./:/opt
  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "5431:5432"
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
    name: votong_database-data
