[tool.ruff]
# Enable the following rules
# More info: https://docs.astral.sh/ruff/rules/

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "migrations",
    "legacy_settings",
]

# Same as Black.
line-length = 120

# Assume Python 3.11.
target-version = "py311"

[lint]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
ignore = []

select = [
    "DJ", # Flake8-Django - https://docs.astral.sh/ruff/rules/#flake8-django-dj
    "E", # Pycodestyle errors - https://docs.astral.sh/ruff/rules/#error-e
    "W", # Pycodestyle warnings - https://docs.astral.sh/ruff/rules/#warning-w
    "F", # Pyflakes - https://docs.astral.sh/ruff/rules/#pyflakes-f
    "T10", # Debugger - https://docs.astral.sh/ruff/rules/#flake8-debugger-t10
    "T20", # Remove print/pprint statements - https://docs.astral.sh/ruff/rules/#flake8-print-t20
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

[tool.ruff.lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.ruff.lint.extend-per-file-ignores]
"users/models.py" = ["DJ001"]
"test_settings.py" = ["F403", "F405"]
"*/__init__.py" = ["F401"]

[pytest]
DJANGO_SETTINGS_MODULE = "factory.test_settings"

python_files = [
    "test.py",
    "test*.py",
    "*test.py",
    "*tests.py",
    "backend/*/tests/*.py",
]
filterwarnings = [
    "ignore:The django.utils.baseconv module is deprecated."
]

[tool.black]
line-length = 120
target-version = ["py311"]
extend-exclude = '''(
    (.+/)?migrations/.+
    | (.+/)?auditlog/.+
)'''

[tool.isort]
line_length = 120
indent = "    "
multi_line_output = 3
combine_as_imports = true
include_trailing_comma = true
known_tests = "tests"
known_first_party = "civil_society_vote,hub"
default_section = "THIRDPARTY"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER,TESTS"
