[tool.black]
line-length = 120

[tool.isort]
line_length = 120
indent = "    "
multi_line_output = 3
combine_as_imports = true
include_trailing_comma = true
known_tests = "tests"
known_first_party = "civil_society_vote,hub"
default_section = "THIRDPARTY"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER,TESTS"
