#!/bin/bash

PORT=${PORT:-"8010"}

LOAD_DUMMY_DATA=${LOAD_DUMMY_DATA:-"no"}

RUN_MIGRATION=${RUN_MIGRATION:-"yes"}
RUN_INITIALIZATION=${RUN_INITIALIZATION:-"yes"}
RUN_COLLECT_STATIC=${RUN_COLLECT_STATIC:-"no"}
RUN_DEV_SERVER=${RUN_DEV_SERVER:-"yes"}

echo "Run basic health checks"
./manage.py check

if [[ $RUN_MIGRATION = yes ]] ; then
  echo "Run database migrations"
  ./manage.py migrate
fi

if [[ $RUN_INITIALIZATION = yes ]] ; then
  echo "Add functional data to the system"
  ./manage.py init
fi

if [[ $LOAD_DUMMY_DATA = yes ]] ; then
  echo "Load dummy data in the database"
  ./manage.py seed
fi

if [[ $RUN_COLLECT_STATIC = yes ]] ; then
  echo "Collect static files"
  mkdir -p staticfiles
  ./manage.py collectstatic --noinput
fi

if [[ $RUN_DEV_SERVER = yes ]] ; then
  echo "Start web server on $PORT"
  ./manage.py runserver_plus "0.0.0.0:$PORT"
else
   gunicorn civil_society_vote.wsgi --bind "0.0.0.0:$PORT" --log-level info -k gevent -w 10 -t 90
fi
