#!/bin/sh

PORT=${PORT:-"8000"}

RUN_SEED=${RUN_SEED:-"yes"}
RUN_MIGRATION=${RUN_MIGRATION:-"yes"}
RUN_DEV_SERVER=${RUN_DEV_SERVER:-"yes"}
RUN_COLLECT_STATIC=${RUN_COLLECT_STATIC:-"no"}
RUN_CREATE_SUPER_USER=${RUN_CREATE_SUPER_USER:-"no"}

echo "Checking..."
./manage.py check

if [ "$RUN_MIGRATION" = "yes" ] ; then
  echo "Migrating databse"
  ./manage.py migrate --run-syncdb
fi

if [ "$RUN_COLLECT_STATIC" = "yes" ] ; then
  echo "Collect static"
  mkdir -p static
  ./manage.py collectstatic --noinput
fi

if [ "$RUN_SEED" = "yes" ] ; then
  echo "Seed"
  ./manage.py seed
fi

if [ "$RUN_CREATE_USER_USER" = "yes" ] ; then
  echo "Create superuser"
  ./manage.py createsuperuser --noinput
fi

if [ "$RUN_DEV_SERVER" = "yes" ] ; then
  echo "Start web server on $PORT"
  ./manage.py runserver "0.0.0.0:$PORT"
else
   gunicorn civil_society_vote.wsgi --bind "0.0.0.0:$PORT" --log-level info -k gevent -w 10
fi
