# Generated by Django 2.2.12 on 2020-06-05 07:07

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                ("role", models.CharField(max_length=254, verbose_name="Role")),
                ("founder", models.BooleanField(default=False, verbose_name="Founder/Associate")),
                ("representative", models.BooleanField(default=False, verbose_name="Legal representative")),
                ("board_member", models.BooleanField(default=False, verbose_name="Board member")),
                ("experience", models.TextField(verbose_name="Professional experience")),
                ("studies", models.TextField(verbose_name="Studies")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=30, verbose_name="Phone")),
                (
                    "photo",
                    models.ImageField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "mandate",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Mandate from the organization",
                    ),
                ),
                (
                    "letter",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Letter of intent",
                    ),
                ),
                (
                    "statement",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Statement of conformity",
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Curriculum Vitae",
                    ),
                ),
                (
                    "legal_record",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Legal record",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate",
                "verbose_name_plural": "Candidates",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("county", models.CharField(max_length=50, verbose_name="County")),
                ("is_county_residence", models.BooleanField(default=False, verbose_name="Is county residence")),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "unique_together": {("city", "county")},
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=254, unique=True, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="NGO Name")),
                ("description", models.TextField(verbose_name="Description")),
                ("reg_com_number", models.CharField(max_length=20, verbose_name="Registration number")),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        verbose_name="Current state",
                    ),
                ),
                ("purpose_initial", models.CharField(max_length=254, verbose_name="Initial purpose")),
                ("purpose_current", models.CharField(max_length=254, verbose_name="Current purpose")),
                ("founders", models.CharField(max_length=254, verbose_name="Founders/Associates")),
                ("representative", models.CharField(max_length=254, verbose_name="Legal representative")),
                ("board_council", models.CharField(max_length=254, verbose_name="Board council")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=30, verbose_name="Phone")),
                (
                    "county",
                    models.CharField(
                        choices=[
                            ("Alba", "Alba"),
                            ("Arad", "Arad"),
                            ("Arges", "Arges"),
                            ("Bacau", "Bacau"),
                            ("Bihor", "Bihor"),
                            ("Bistrita-Nasaud", "Bistrita-Nasaud"),
                            ("Botosani", "Botosani"),
                            ("Braila", "Braila"),
                            ("Brasov", "Brasov"),
                            ("Bucuresti", "Bucuresti"),
                            ("Buzau", "Buzau"),
                            ("Caras-Severin", "Caras-Severin"),
                            ("Calarasi", "Calarasi"),
                            ("Cluj", "Cluj"),
                            ("Constanta", "Constanta"),
                            ("Covasna", "Covasna"),
                            ("Dambovita", "Dambovita"),
                            ("Dolj", "Dolj"),
                            ("Galati", "Galati"),
                            ("Giurgiu", "Giurgiu"),
                            ("Gorj", "Gorj"),
                            ("Harghita", "Harghita"),
                            ("Hunedoara", "Hunedoara"),
                            ("Ialomita", "Ialomita"),
                            ("Iasi", "Iasi"),
                            ("Ilfov", "Ilfov"),
                            ("Maramures", "Maramures"),
                            ("Mehedinti", "Mehedinti"),
                            ("Mures", "Mures"),
                            ("Neamt", "Neamt"),
                            ("Olt", "Olt"),
                            ("Prahova", "Prahova"),
                            ("Satu Mare", "Satu Mare"),
                            ("Salaj", "Salaj"),
                            ("Sibiu", "Sibiu"),
                            ("Suceava", "Suceava"),
                            ("Teleorman", "Teleorman"),
                            ("Timis", "Timis"),
                            ("Tulcea", "Tulcea"),
                            ("Vaslui", "Vaslui"),
                            ("Valcea", "Valcea"),
                            ("Vrancea", "Vrancea"),
                        ],
                        max_length=50,
                        verbose_name="County",
                    ),
                ),
                ("address", models.CharField(max_length=254, verbose_name="Address")),
                (
                    "logo",
                    models.ImageField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "last_balance_sheet",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="First page of last balance sheet",
                    ),
                ),
                (
                    "statute",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="NGO Statute",
                    ),
                ),
                (
                    "letter",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Letter of intent",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="hub.City", verbose_name="City"
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="orgs", to="hub.Domain"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orgs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationVote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("abstention", "Abstention")],
                        default="abstention",
                        max_length=10,
                        verbose_name="Vote",
                    ),
                ),
                ("motivation", models.TextField(verbose_name="Motivation")),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="hub.Organization"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Organization vote",
                "verbose_name_plural": "Organization votes",
            },
        ),
        migrations.CreateModel(
            name="CandidateVote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="hub.Candidate"
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="votes", to="hub.Domain"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Candidate vote",
                "verbose_name_plural": "Canditate votes",
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="candidates", to="hub.Domain"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="org",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="candidate", to="hub.Organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationvote",
            constraint=models.UniqueConstraint(fields=("user", "org"), name="unique_org_vote"),
        ),
        migrations.AddConstraint(
            model_name="candidatevote",
            constraint=models.UniqueConstraint(fields=("user", "candidate"), name="unique_candidate_vote"),
        ),
        migrations.AddConstraint(
            model_name="candidatevote",
            constraint=models.UniqueConstraint(fields=("user", "domain"), name="unique_candidate_domain_vote"),
        ),
    ]
