# Generated by Django 2.2.13 on 2020-06-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_add_romanian_unaccent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={"ordering": ["name"], "verbose_name": "Candidate", "verbose_name_plural": "Candidates"},
        ),
    ]
