# Generated by Django 2.2.16 on 2020-09-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0004_featureflag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="domain",
        ),
    ]
