# Generated by Django 2.2.16 on 2020-10-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0008_auto_20201001_0036"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("view_data_candidate", "View data candidate"),
                    ("approve_candidate", "Approve candidate"),
                    ("support_candidate", "Support candidate"),
                    ("vote_candidate", "Vote candidate"),
                ),
                "verbose_name": "Candidate",
                "verbose_name_plural": "Candidates",
            },
        ),
    ]
