# Generated by Django 2.2.16 on 2020-10-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0009_auto_20201001_0750"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("view_data_organization", "View data organization"),
                    ("approve_organization", "Approve organization"),
                ),
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
    ]
