# Generated by Django 2.2.16 on 2020-10-01 14:49

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0010_auto_20201001_0814"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[(0, "dummy")],
                default="pending",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
            ),
        ),
    ]
