# Generated by Django 2.2.16 on 2020-10-04 18:52

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hub", "0013_emailtemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateSupporter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="supporters", to="hub.Candidate"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Candidate supporter",
                "verbose_name_plural": "Canditate supporters",
            },
        ),
        migrations.AddConstraint(
            model_name="candidatesupporter",
            constraint=models.UniqueConstraint(fields=("user", "candidate"), name="unique_candidate_supporter"),
        ),
    ]
