# Generated by Django 2.2.16 on 2020-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0017_auto_20201005_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="is_proposed",
            field=models.BooleanField(default=False, verbose_name="Is proposed?"),
        ),
    ]
