# Generated by Django 2.2.16 on 2020-10-05 20:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0018_candidate_is_proposed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="statement",
            field=models.FileField(
                help_text="Descarcă modelul de aici https://drive.google.com/file/d/1BOquxpQnuCPmhlt9HFjklCY_oZARVlz1/view?usp=sharing",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Statement of interests",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="fiscal_certificate",
            field=models.FileField(
                blank=True,
                help_text="Certificat fiscal emis în ultimele 6 luni",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Fiscal certificate",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="report_2017",
            field=models.FileField(
                blank=True,
                help_text="Rapoartele anuale trebuie să includă sursele de finanțare din care să rezulte că organizația dispune de resurse financiare şi materiale pentru îndeplinirea mandatului de reprezentare a organizaţiilor votante în CES.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Yearly report 2017",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="report_2018",
            field=models.FileField(
                blank=True,
                help_text="Rapoartele anuale trebuie să includă sursele de finanțare din care să rezulte că organizația dispune de resurse financiare şi materiale pentru îndeplinirea mandatului de reprezentare a organizaţiilor votante în CES.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Yearly report 2018",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="report_2019",
            field=models.FileField(
                blank=True,
                help_text="Rapoartele anuale trebuie să includă sursele de finanțare din care să rezulte că organizația dispune de resurse financiare şi materiale pentru îndeplinirea mandatului de reprezentare a organizaţiilor votante în CES.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Yearly report 2019",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="statement",
            field=models.FileField(
                blank=True,
                help_text="Declarație pe proprie răspundere prin care declară că nu realizează activități sau susține cauze de natură politică sau care discriminează pe considerente legate de etnie, rasă, sex, orientare sexuală, religie, capacități fizice sau psihice sau de apartenența la una sau mai multe categorii sociale sau economice.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Statement",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="statute",
            field=models.FileField(
                blank=True,
                help_text="Copie a ultimului statut autentificat al organizației și a hotărârii judecătorești corespunzătoare, definitivă şi irevocabilă și copii ale tuturor documentelor ulterioare/ suplimentare ale statutului, inclusiv hotărârile judecătorești definitive și irevocabile; Vă rugăm să arhivați documentele și să încărcați o singură arhivă în platformă.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="NGO Statute",
            ),
        ),
    ]
