# Generated by Django 2.2.16 on 2020-10-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0020_auto_20201006_0742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="accept_terms_and_conditions",
            field=models.BooleanField(verbose_name="I agree to the Terms and Conditions of the VotONG platform"),
        ),
    ]
