# Generated by Django 2.2.16 on 2020-10-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0020_auto_20201006_0613"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="registration_number",
            field=models.CharField(default="", max_length=20, verbose_name="Registration number"),
            preserve_default=False,
        ),
    ]
