# Generated by Django 4.2.13 on 2024-07-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0042_organization_ngohub_org_id_organization_report_2021_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo_url",
            field=models.URLField(blank=True, max_length=300, verbose_name="Logo URL"),
        ),
    ]
