# Generated by Django 4.2.13 on 2024-07-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0045_alter_organization_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="organisation_head_name",
            new_name="organization_head_name",
        ),
    ]
