# Generated by Django 4.2.13 on 2024-07-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0048_alter_featureflag_flag"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailTemplate",
        ),
        migrations.AlterModelOptions(
            name="candidateconfirmation",
            options={"verbose_name": "Candidate confirmation", "verbose_name_plural": "Candidate confirmations"},
        ),
        migrations.AlterModelOptions(
            name="candidatevote",
            options={"verbose_name": "Candidate vote", "verbose_name_plural": "Candidate votes"},
        ),
    ]
