# Generated by Django 4.2.13 on 2024-07-09 09:11

from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0051_alter_organization_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.FileField(
                blank=True,
                default="",
                max_length=300,
                storage=hub.models.select_public_storage,
                upload_to="",
                verbose_name="Logo",
            ),
        ),
    ]
