# Generated by Django 4.2.13 on 2024-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0052_alter_organization_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending approval"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="draft",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
