# Generated by Django 4.2.13 on 2024-07-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0053_alter_candidate_status_alter_organization_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="city",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="hub.city", verbose_name="City"
            ),
        ),
    ]
