# Generated by Django 4.2.13 on 2024-07-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0054_alter_organization_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="ngohub_last_update",
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Last NGO Hub update"),
        ),
    ]
