# Generated by Django 4.2.14 on 2024-07-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0055_organization_ngohub_last_update_ended_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="report_2017",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="report_2018",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="report_2019",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="report_2020",
        ),
    ]
