# Generated by Django 4.2.14 on 2024-08-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0060_alter_featureflag_flag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="organization_head_name",
        ),
        migrations.AlterField(
            model_name="organization",
            name="board_council",
            field=models.CharField(blank=True, default="", max_length=1000, verbose_name="Board council"),
        ),
    ]
