# Generated by Django 4.2.14 on 2024-08-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0061_remove_organization_organization_head_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
