# Generated by Django 4.2.14 on 2024-08-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0062_alter_candidate_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="criminal_record",
            field=models.FileField(
                blank=True,
                help_text="(Optional) Criminal record, valid at the time of submitting the candidacy",
                max_length=300,
                null=True,
                upload_to="",
                verbose_name="Criminal record",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="cv",
            field=models.FileField(
                blank=True, help_text="Europass format CV", max_length=300, null=True, upload_to="", verbose_name="CV"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="declaration_of_interests",
            field=models.FileField(
                blank=True,
                help_text="Official format Declaration of interests",
                max_length=300,
                null=True,
                upload_to="",
                verbose_name="Declaration of interests",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="fiscal_record",
            field=models.FileField(
                blank=True,
                help_text="Fiscal record, valid at the time of submitting the candidacy",
                max_length=300,
                null=True,
                upload_to="",
                verbose_name="Fiscal record",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="letter_of_intent",
            field=models.FileField(
                blank=True,
                help_text="Letter of intent (with the mention of the domain to be represented in the CES)",
                max_length=300,
                null=True,
                upload_to="",
                verbose_name="Letter of intent",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="mandate",
            field=models.FileField(
                blank=True,
                help_text="Mandate from the organization (signed in original + electronic) with the highlighting of the domain for which it is running",
                max_length=300,
                null=True,
                upload_to="",
                verbose_name="Mandate",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The name of the designated person who will represent the organization in the Electoral Commission in case of a favorable response.The designated person must be an employee of the organization and part of its management structures (member of the Board of Directors, Executive Director, etc.).",
                max_length=254,
                verbose_name="Representative name",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="The role of the designated person in the organization.",
                max_length=254,
                verbose_name="Representative role in organization",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="statement",
            field=models.FileField(
                blank=True,
                help_text="Declaration of the designated representative stating that he/she is not a member of the leadership of a political party, has not been elected to a public office and is not a dignitary of the Romanian state.",
                max_length=300,
                null=True,
                upload_to="",
                verbose_name="Representative statement",
            ),
        ),
    ]
