# Generated by Django 4.2.16 on 2024-10-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0066_organization_voting_domain_alter_candidate_domain_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="user",
        ),
    ]
