# Generated by Django 4.2.16 on 2024-11-12 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0068_alter_candidate_criminal_record_alter_candidate_cv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="activity_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Summary of the activities carried out by the organization in the current year (between 500 and 2000 characters)",
                max_length=2000,
                validators=[django.core.validators.MinLengthValidator(500)],
                verbose_name="Current year activity summary",
            ),
        ),
    ]
