# Generated by Django 4.2.16 on 2024-11-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0069_organization_activity_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The name of the designated person in the organization.",
                max_length=254,
                verbose_name="Representative name",
            ),
        ),
    ]
