# Generated by Django 4.2.16 on 2024-11-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0070_alter_candidate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending approval"),
                    ("ngohub_accepted", "NGO Hub accepted"),
                    ("accepted", "Accepted"),
                    ("admin", "Admin"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="draft",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
