# Generated by Django 4.2.16 on 2024-11-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0071_alter_organization_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "In Validation"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
