# Generated by Django 4.2.16 on 2024-11-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0072_alter_candidate_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="county",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="County"),
        ),
    ]
