# Generated by Django 4.2.16 on 2024-11-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0073_alter_organization_county"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending candidate"),
                    ("accepted", "Accepted candidate"),
                    ("confirmed", "Validated candidate"),
                    ("rejected", "Rejected candidate"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="flag",
            field=models.CharField(
                choices=[
                    ("enable_org_registration", "Enable organization registration"),
                    ("enable_org_editing", "Enable organization editing"),
                    ("enable_org_approval", "Enable organization approvals"),
                    ("enable_candidate_registration", "Enable candidate registration"),
                    ("enable_candidate_editing", "Enable candidate editing"),
                    ("enable_candidate_supporting", "Enable candidate supporting"),
                    ("enable_candidate_voting", "Enable candidate voting"),
                    ("enable_candidate_confirmation", "Enable candidate confirmation"),
                    ("enable_results_display", "Enable the display of results"),
                    ("single_domain_round", "Voting round with just one domain (some restrictions will apply)"),
                    (
                        "global_support_round",
                        "Enable global support (the support of at least 10 organizations is required)",
                    ),
                    ("enable_voting_domain", "Enable the voting domain restriction for an organization"),
                ],
                max_length=254,
                unique=True,
                verbose_name="Flag",
            ),
        ),
    ]
