# Generated by Django 4.2.16 on 2024-11-21 13:40

from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0074_alter_candidate_status_alter_featureflag_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="statement",
            field=models.FileField(
                blank=True,
                help_text="Declaration of the designated representative stating that he/she is not a member of the leadership of a political party, has not been elected to a public office and is not a dignitary of the Romanian state, has no criminal record.",
                max_length=300,
                null=True,
                upload_to="",
                validators=[hub.models.file_validator],
                verbose_name="Representative statement",
            ),
        ),
    ]
