# Generated by Django 4.2.16 on 2024-11-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0075_alter_candidate_statement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("view_data_candidate", "View data candidate"),
                    ("approve_candidate", "Approve candidate"),
                    ("reset_approve_candidate", "Reset candidate approval"),
                    ("support_candidate", "Support candidate"),
                    ("vote_candidate", "Vote candidate"),
                ),
                "verbose_name": "Candidate",
                "verbose_name_plural": "Candidates",
            },
        ),
    ]
