# Generated by Django 2.2.12 on 2020-05-20 08:58

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                ("role", models.CharField(max_length=254, verbose_name="Role")),
                ("experience", models.TextField(verbose_name="Professional experience")),
                ("studies", models.TextField(verbose_name="Studies")),
                ("founder", models.BooleanField(default=False, verbose_name="Founder/Associate")),
                ("representative", models.BooleanField(default=False, verbose_name="Legal representative")),
                ("board_member", models.BooleanField(default=False, verbose_name="Board member")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=30, verbose_name="Phone")),
                (
                    "photo",
                    models.ImageField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "domain",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Academic and professional"),
                            (2, "Education and health"),
                            (3, "Agricultural and cooperative"),
                            (4, "Environmental"),
                            (5, "Social, family, people with disabilities and the elderly"),
                            (6, "Human rights"),
                        ],
                        verbose_name="Domain",
                    ),
                ),
                (
                    "mandate",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Mandate from the organization",
                    ),
                ),
                (
                    "letter",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Letter of intent",
                    ),
                ),
                (
                    "statement",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Statement of conformity",
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="CV",
                    ),
                ),
                (
                    "legal_record",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Legal record",
                    ),
                ),
            ],
            options={"verbose_name": "Candidate", "verbose_name_plural": "Candidates",},
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("county", models.CharField(max_length=50, verbose_name="County")),
                ("is_county_residence", models.BooleanField(default=False, verbose_name="Is county residence")),
            ],
            options={"verbose_name": "City", "verbose_name_plural": "cities", "unique_together": {("city", "county")},},
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("name", models.CharField(max_length=254, verbose_name="NGO Name")),
                (
                    "domain",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Academic and professional"),
                            (2, "Education and health"),
                            (3, "Agricultural and cooperative"),
                            (4, "Environmental"),
                            (5, "Social, family, people with disabilities and the elderly"),
                            (6, "Human rights"),
                        ],
                        verbose_name="Domain",
                    ),
                ),
                ("reg_com_number", models.CharField(max_length=20, verbose_name="Registration number")),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        verbose_name="Current state",
                    ),
                ),
                ("purpose_initial", models.CharField(max_length=254, verbose_name="Initial purpose")),
                ("purpose_current", models.CharField(max_length=254, verbose_name="Current purpose")),
                ("founders", models.CharField(max_length=254, verbose_name="Founders/Associates")),
                ("representative", models.CharField(max_length=254, verbose_name="Legal representative")),
                ("board_council", models.CharField(max_length=254, verbose_name="Board council")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=30, verbose_name="Phone")),
                ("county", models.CharField(max_length=50, verbose_name="County")),
                ("address", models.CharField(max_length=254, verbose_name="Address")),
                (
                    "logo",
                    models.ImageField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "last_balance_sheet",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="First page of last balance sheet",
                    ),
                ),
                (
                    "statute",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="NGO Statute",
                    ),
                ),
                (
                    "letter",
                    models.FileField(
                        max_length=300,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to="",
                        verbose_name="Letter of intent",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="hub.City", verbose_name="City"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Organization", "verbose_name_plural": "Organizations", "ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="OrganizationVote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "domain",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Academic and professional"),
                            (2, "Education and health"),
                            (3, "Agricultural and cooperative"),
                            (4, "Environmental"),
                            (5, "Social, family, people with disabilities and the elderly"),
                            (6, "Human rights"),
                        ],
                        verbose_name="Domain",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[("yes", "YES"), ("no", "NO"), ("abstention", "ABSTENTION")],
                        default="abstention",
                        max_length=10,
                        verbose_name="Vote",
                    ),
                ),
                (
                    "motivation",
                    models.TextField(
                        blank=True,
                        help_text="Motivate your decision",
                        max_length=500,
                        null=True,
                        verbose_name="Motivation",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="hub.Organization"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Organization vote", "verbose_name_plural": "Organization votes",},
        ),
        migrations.CreateModel(
            name="CandidateVote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "domain",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Academic and professional"),
                            (2, "Education and health"),
                            (3, "Agricultural and cooperative"),
                            (4, "Environmental"),
                            (5, "Social, family, people with disabilities and the elderly"),
                            (6, "Human rights"),
                        ],
                        verbose_name="Domain",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="hub.Candidate"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Organization vote", "verbose_name_plural": "Organization votes",},
        ),
        migrations.AddField(
            model_name="candidate",
            name="org",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="hub.Organization"),
        ),
        migrations.AddConstraint(
            model_name="organizationvote",
            constraint=models.UniqueConstraint(fields=("user", "org"), name="unique_org_vote"),
        ),
        migrations.AddConstraint(
            model_name="organizationvote",
            constraint=models.UniqueConstraint(fields=("user", "domain"), name="unique_org_domain_vote"),
        ),
        migrations.AlterUniqueTogether(name="organizationvote", unique_together={("user", "domain"), ("user", "org")},),
        migrations.AddConstraint(
            model_name="candidatevote",
            constraint=models.UniqueConstraint(fields=("user", "candidate"), name="unique_candidate_vote"),
        ),
        migrations.AddConstraint(
            model_name="candidatevote",
            constraint=models.UniqueConstraint(fields=("user", "domain"), name="unique_candidate_domain_vote"),
        ),
    ]
