# Generated by Django 2.2.12 on 2020-05-26 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_auto_20200522_2117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="org",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="candidate", to="hub.Organization"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orgs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
