# Generated by Django 2.2.14 on 2020-07-11 09:31
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


def create_initial_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("hub", "FeatureFlag")
    FeatureFlag.objects.get_or_create(flag="enable_org_voting", status="off")
    FeatureFlag.objects.get_or_create(flag="enable_candidate_voting", status="off")


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_auto_20200609_1750"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("on", "ON"), ("off", "OFF")],
                        default="on",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("enable_org_voting", "Enable organization voting"),
                            ("enable_candidate_voting", "Enable candidate voting"),
                        ],
                        max_length=254,
                        unique=True,
                        verbose_name="Flag",
                    ),
                ),
            ],
            options={"verbose_name": "Feature flag", "verbose_name_plural": "Feature flags",},
        ),
        migrations.RunPython(create_initial_flags),
    ]
