# Generated by Django 2.2.16 on 2020-09-30 15:57

import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0005_remove_organization_domain"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("approve_candidate", "Approve candidate"),
                    ("support_candidate", "Support candidate"),
                    ("vote_candidate", "Vote candidate"),
                ),
                "verbose_name": "Candidate",
                "verbose_name_plural": "Candidates",
            },
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["name"],
                "permissions": (("approve_organization", "Approve organization"),),
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="flag",
            field=models.CharField(
                choices=[
                    ("enable_org_registration", "Enable organization registration"),
                    ("enable_org_approval", "Enable organization approvals"),
                    ("enable_candidate_registration", "Enable candidate registration"),
                    ("enable_org_voting", "Enable organization voting"),
                    ("enable_candidate_voting", "Enable candidate voting"),
                ],
                max_length=254,
                unique=True,
                verbose_name="Flag",
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[(0, "dummy")], default="off", max_length=100, no_check_for_status=True, verbose_name="status"
            ),
        ),
    ]
