# Generated by Django 2.2.16 on 2020-10-01 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0006_auto_20200930_1557"),
    ]

    operations = [
        migrations.DeleteModel(name="OrganizationVote",),
    ]
