# Generated by Django 2.2.16 on 2020-10-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0007_delete_organizationvote"),
    ]

    operations = [
        migrations.RemoveField(model_name="featureflag", name="status",),
        migrations.RemoveField(model_name="featureflag", name="status_changed",),
        migrations.AddField(model_name="featureflag", name="is_enabled", field=models.BooleanField(default=False),),
    ]
