# Generated by Django 2.2.16 on 2020-10-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0014_auto_20201004_1852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="flag",
            field=models.CharField(
                choices=[
                    ("enable_org_registration", "Enable organization registration"),
                    ("enable_org_approval", "Enable organization approvals"),
                    ("enable_org_voting", "Enable organization voting"),
                    ("enable_candidate_registration", "Enable candidate registration"),
                    ("enable_candidate_supporting", "Enable candidate supporting"),
                    ("enable_candidate_voting", "Enable candidate voting"),
                ],
                max_length=254,
                unique=True,
                verbose_name="Flag",
            ),
        ),
    ]
