# Generated by Django 2.2.16 on 2020-10-05 14:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0016_auto_20201004_2028"),
    ]

    operations = [
        migrations.RemoveField(model_name="candidate", name="board_member",),
        migrations.RemoveField(model_name="candidate", name="founder",),
        migrations.RemoveField(model_name="candidate", name="legal_record",),
        migrations.RemoveField(model_name="candidate", name="representative",),
        migrations.RemoveField(model_name="organization", name="last_balance_sheet",),
        migrations.AddField(
            model_name="candidate",
            name="legal_records",
            field=models.FileField(
                blank=True,
                help_text="Cazier judiciar (optional)",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Legal records",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="tax_records",
            field=models.FileField(
                help_text="Cazier fiscal, valabil la data depunerii candidaturii",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Tax records",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="fiscal_certificate",
            field=models.FileField(
                help_text="Certificat fiscal emis în ultimele 6 luni",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Fiscal certificate",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="report_2017",
            field=models.FileField(
                help_text="Rapoartele anuale trebuie să includă sursele de finanțare din care să rezulte că organizația dispune de resurse financiare şi materiale pentru îndeplinirea mandatului de reprezentare a organizaţiilor votante în CES.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Yearly report 2017",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="report_2018",
            field=models.FileField(
                help_text="Rapoartele anuale trebuie să includă sursele de finanțare din care să rezulte că organizația dispune de resurse financiare şi materiale pentru îndeplinirea mandatului de reprezentare a organizaţiilor votante în CES.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Yearly report 2018",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="report_2019",
            field=models.FileField(
                help_text="Rapoartele anuale trebuie să includă sursele de finanțare din care să rezulte că organizația dispune de resurse financiare şi materiale pentru îndeplinirea mandatului de reprezentare a organizaţiilor votante în CES.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Yearly report 2019",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="statement",
            field=models.FileField(
                help_text="Declarație pe proprie răspundere prin care declară că nu realizează activități sau susține cauze de natură politică sau care discriminează pe considerente legate de etnie, rasă, sex, orientare sexuală, religie, capacități fizice sau psihice sau de apartenența la una sau mai multe categorii sociale sau economice.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Statement",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="description",
            field=models.TextField(max_length=1000, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="experience",
            field=models.TextField(max_length=2000, verbose_name="Professional experience"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="letter",
            field=models.FileField(
                help_text="Scrisoare de intenție (cu menționarea domeniului pe care dorește să-l reprezinte în cadrul CES) din care să rezulte desfăşurarea de activităţi de influenţare a politicilor publice și de reprezentare a intereselor unor grupuri de organizaţii care desfăşoară o activitate de interes public",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Letter of intent",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="mandate",
            field=models.FileField(
                help_text="Mandat din partea organizației (semnat - inclusiv prin semnatură electronică)",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Mandate from the organization",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="role",
            field=models.CharField(max_length=254, verbose_name="Role in organization"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="statement",
            field=models.FileField(
                help_text="Declarație de interese (descarcă modelul de aici https://drive.google.com/file/d/1BOquxpQnuCPmhlt9HFjklCY_oZARVlz1/view?usp=sharing)",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Statement of conformity",
            ),
        ),
        migrations.AlterField(
            model_name="candidate", name="studies", field=models.TextField(max_length=2000, verbose_name="Studies"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="statute",
            field=models.FileField(
                help_text="Copie a ultimului statut autentificat al organizației și a hotărârii judecătorești corespunzătoare, definitivă şi irevocabilă și copii ale tuturor documentelor ulterioare/ suplimentare ale statutului, inclusiv hotărârile judecătorești definitive și irevocabile; Vă rugăm să arhivați documentele și să încărcați o singură arhivă în platformă.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="NGO Statute",
            ),
        ),
    ]
