# Generated by Django 2.2.16 on 2020-10-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0019_auto_20201005_2044"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="accept_terms_and_conditions",
            field=models.BooleanField(default=False, verbose_name="Terms and conditions"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="politic_members",
            field=models.BooleanField(
                default=False,
                verbose_name="I declare that the members of the management of the organization I represent (the President and the members of the Board of Directors) are not members of political parties.",
            ),
            preserve_default=False,
        ),
    ]
