# Generated by Django 2.2.16 on 2020-10-06 06:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0019_auto_20201005_2044"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="last_balance_sheet",
            field=models.FileField(
                help_text="Prima pagină a ultimului bilanț contabil depus la Ministerul Finanțelor",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="First page of last balance sheet",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="statute",
            field=models.FileField(
                help_text="Copie a ultimului statut autentificat al organizației și a hotărârii judecătorești corespunzătoare, definitivă şi irevocabilă și copii ale tuturor documentelor ulterioare/suplimentare ale statutului, inclusiv hotărârile judecătorești definitive și irevocabile; Vă rugăm să arhivați documentele și să încărcați o singură arhivă în platformă.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="NGO Statute",
            ),
        ),
    ]
