# Generated by Django 2.2.16 on 2020-10-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0021_auto_20201006_0744"),
        ("hub", "0021_organization_registration_number"),
    ]

    operations = []
