# Generated by Django 2.2.16 on 2020-10-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0027_organization_politic_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="accept_terms_and_conditions",
            field=models.BooleanField(verbose_name="Accepted Terms and Conditions"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="politic_members",
            field=models.BooleanField(blank=True, null=True, verbose_name="Has political party members"),
        ),
    ]
