# Generated by Django 2.2.16 on 2020-10-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0029_auto_20201015_1024"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="rejection_message",
            field=models.TextField(blank=True, verbose_name="Rejection message"),
        ),
    ]
