# Generated by Django 2.2.16 on 2020-11-03 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0031_auto_20201025_2147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="initial_org",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is set, the `org` field will be unset and the candidate is removed as the official proposal of the organization.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="hub.Organization",
            ),
        ),
    ]
