# Generated by Django 2.2.16 on 2020-11-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0032_auto_20201103_0847"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template",
            field=models.CharField(
                choices=[
                    ("pending_orgs_digest", "Pending organizations digest email"),
                    ("org_approved", "Your organization was approved"),
                    ("org_rejected", "Your organization was rejected"),
                    ("vote_audit", "Vote audit log"),
                ],
                max_length=254,
                unique=True,
                verbose_name="Template",
            ),
        ),
    ]
