# Generated by Django 2.2.16 on 2020-11-04 10:07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hub", "0033_auto_20201103_0954"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template",
            field=models.CharField(
                choices=[
                    ("pending_orgs_digest", "Pending organizations digest email"),
                    ("org_approved", "Your organization was approved"),
                    ("org_rejected", "Your organization was rejected"),
                    ("vote_audit", "Vote audit log"),
                    ("confirmation", "Confirmation email"),
                ],
                max_length=254,
                unique=True,
                verbose_name="Template",
            ),
        ),
        migrations.CreateModel(
            name="CandidateConfirmation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="confirmations", to="hub.Candidate"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Candidate confirmation", "verbose_name_plural": "Canditate confirmations",},
        ),
        migrations.AddConstraint(
            model_name="candidateconfirmation",
            constraint=models.UniqueConstraint(fields=("user", "candidate"), name="unique_candidate_confirmation"),
        ),
    ]
