# Generated by Django 2.2.19 on 2021-03-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0035_auto_20201107_1612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="seats",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Numărul de locuri disponibile într-un domeniu este egal cu numărul de voturi pe are un elector le poate exprima în acel domeniu. Setând numărul de locuri se setează și numărul maxim de voturi.",
                verbose_name="Number of seats",
            ),
        ),
    ]
