# Generated by Django 2.2.24 on 2021-11-14 15:43

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0038_auto_20211109_2107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidates",
                to="hub.Domain",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Numele persoanei care va reprezenta organizatia in Comisia Electorală în cazul unui răspuns favorabil. Persoana desemnată trebuie să fie angajat în cadrul organizației și parte din structurile de conducere ale acesteia (membru în Consiliul Director, Director Executiv etc)",
                max_length=254,
                verbose_name="Representative name",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="Funcția în organizației a persoanei desemnate.",
                max_length=254,
                verbose_name="Representative role in organization",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="statement",
            field=models.FileField(
                blank=True,
                help_text="Declarație pe propria răspundere a reprezentantului desemnat prin care declară că nu este membru al conducerii unui partid politic, nu a fost ales într-o funcție publică și nu este demnitar al statului român.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Representative statement",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="report_2017",
            field=models.FileField(
                blank=True,
                help_text="Rapoartele anuale trebuie să includă sursele de finanțare din care să rezulte că organizația dispune de resurse financiare şi umane pentru îndeplinirea mandatului de membru în Comisia Electorală a VotONG.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Yearly report 2017",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="report_2018",
            field=models.FileField(
                blank=True,
                help_text="Rapoartele anuale trebuie să includă sursele de finanțare din care să rezulte că organizația dispune de resurse financiare şi umane pentru îndeplinirea mandatului de membru în Comisia Electorală a VotONG.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Yearly report 2018",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="report_2019",
            field=models.FileField(
                blank=True,
                help_text="Rapoartele anuale trebuie să includă sursele de finanțare din care să rezulte că organizația dispune de resurse financiare şi umane pentru îndeplinirea mandatului de membru în Comisia Electorală a VotONG.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Yearly report 2019",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="report_2020",
            field=models.FileField(
                blank=True,
                help_text="Rapoartele anuale trebuie să includă sursele de finanțare din care să rezulte că organizația dispune de resurse financiare şi umane pentru îndeplinirea mandatului de membru în Comisia Electorală a VotONG.",
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Yearly report 2020",
            ),
        ),
    ]
