# Generated by Django 2.2.19 on 2021-03-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0039_auto_20210318_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='hub.Organization'),
        ),
    ]
