# Generated by Django 2.2.27 on 2022-03-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0039_auto_20211114_1743"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="flag",
            field=models.CharField(
                choices=[
                    ("enable_org_registration", "Enable organization registration"),
                    ("enable_org_approval", "Enable organization approvals"),
                    ("enable_org_voting", "Enable organization voting"),
                    ("enable_candidate_registration", "Enable candidate registration"),
                    ("enable_candidate_supporting", "Enable candidate supporting"),
                    ("enable_candidate_voting", "Enable candidate voting"),
                    ("single_domain_round", "Voting round with just one domain (some restrictions will apply)"),
                ],
                max_length=254,
                unique=True,
                verbose_name="Flag",
            ),
        ),
    ]
