name: Transfer to staging env and run

on: 
  push:
    branches: 
      - develop
      - main

jobs:
  build:
    name: Transfer to dev env and run
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands on dev env
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_SSH_USERNAME }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          script: "/root/votong/deploy/pull.sh"
      
      - name: executing remote ssh commands on production env
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_SSH_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: "/home/ubuntu/civil_society_vote/deploy/pull.sh"
