on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths:
      - 'backend/**'
      - 'docker/**'
      - '.github/workflows/build-image.yml'

name: Build Docker image

jobs:
  build:
    name: Build Docker image
    uses: code4romania/.github/.github/workflows/build-push-image.yml@main
    with:
      images: code4romania/votong
      dockerfile: ./docker/dockerfiles/Dockerfile.backend
    secrets:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
