on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths:
      - 'backend/**'
      - 'docker/**'

name: Build Docker image

jobs:
  build:
    name: Build Docker image
    uses: code4romania/.github/.github/workflows/build-push-image.yml@main
    with:
      image_name: vot-ong
      region: eu-west-1
      dockerfile: ./docker/dockerfiles/Dockerfile.backend
    secrets:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
